# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  # Maintain dependencies for PHP modules
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: widen
    open-pull-requests-limit: 10
    reviewers:
      - jbouse
    pull-request-branch-name:
      separator: "-"
    labels:
      - "composer"
      - "dependencies"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major"]
