nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    csp:
        enabled: true
        compat_headers: false
        hash:
            algorithm: sha512
        enforce:
            browser_adaptive:
                enabled: true
            level1_fallback: true
            report-uri: https://maftkc82.uriports.com/reports/report
            default-src: 
            - 'none'
            base-uri:
            - 'self'
            font-src:
            - 'self'
            script-src:
            - 'self'
            - www.google-analytics.com
            - www.googletagmanager.com/gtag/
            img-src:
            - 'self'
            - 'data:'
            - www.google.com/ads/ga-audiences
            - www.google-analytics.com/collect
            connect-src:
            - 'self'
            - analytics.google.com/g/collect
            - www.google-analytics.com/j/collect
            - stats.g.doubleclick.net/j/collect
            style-src:
            - 'self'
            block-all-mixed-content: true