version: 0.2

phases:
  build:
    commands:
      - composer install
artifacts:
  secondary-artifacts:
    BuildArtifact:
      files:
        - bin/**/*
        - config/**/*
        - migrations/**/*
        - public/**/*
        - src/**/*
        - templates/**/*
        - translations/**/*
        - vendor/**/*
        - .env
        - composer.json
        - composer.lock
        - symfony.lock
        - phpunit.xml.dist
    AssetsArtifact:
      files:
        - 'assets/**/*'
      base-directory: public
      discard-paths: yes
